name: Build and Release

on:
  push:
    branches: [ "master", "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set Version from Tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(grep 'mod_version' gradle.properties | cut -d'=' -f2)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew shadowJar -PmodVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Minecraft-AP-Randomizer-JAR
          path: build/libs/*.jar

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-apworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create minecraft.apworld
        run: |
          cd apworld
          zip -r ../minecraft.apworld .

      - name: Create minecraft_dig.apworld
        run: |
          cd apworlddig
          zip -r ../minecraft_dig.apworld .

      - name: Upload APWorld Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Archipelago-Worlds
          path: "*.apworld"

      - name: Update Release with APWorlds
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "*.apworld"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
